### PR TITLE
Update cjdns.theswissbay.ch peer IP

### PR DESCRIPTION
**Pull request by Serphentas**
Quick update thanks to dynamic IPs !

### CODE REVIEW

**Comment by kpcyrd** [comment]
Hey! Any chance you can move this to a static ip? :)

**Comment by Serphentas** [comment]
Yes, provided I make some adjustments on my end. Please allow a day or two :^)

**Comment by wfleurant** [comment]
@Serphentas It's currently stuck in INIT/UNRESPONSIVE

**Comment by Serphentas** [comment]
Just updated the IP. I'm in the process of changing my ISP so until that happens (4 months tops) it shouldn't change much. Too bad we can't use CNAMEs in place of IPs...

**Comment by wfleurant** [comment]
`80.218.59.16:56879 v20.0000.0000.0000.0013.nuvtkly8swgkwsyyjrv89f4y4y0w3x17w61twgsfh9zv1r87h060.k ESTABLISHED in 5kb/s out 2kb/s "theswissbay.ch"`

**Pull request merged**
