### PR TITLE
Create cjdns.theswissbay.ch

### PR DESCRIPTION
**Pull request by Serphentas**

### CODE REVIEW

**Comment by wfleurant** [comment]
currently unable to connect:

`v0.0000.0000.0000.0015.fc09:eafd:1f1a:7ab5:6e71:c031:37b0:0cab UNRESPONSIVE in 0kb/s out 0kb/s "theswissbay.ch"`

**Comment by Serphentas** [comment]
I just checked my NAT settings, could you give it another go ?

**Comment by wfleurant** [comment]
no go ~25hr try cjdns chat iRC or RiOT in any case

**Comment by wfleurant** [comment]
`v20.0000.0000.0000.0015.nuvtkly8swgkwsyyjrv89f4y4y0w3x17w61twgsfh9zv1r87h060.k ESTABLISHED in 1kb/s out 0kb/s "theswissbay.ch"`

**Comment by Serphentas** [comment]
At last it worked ! Thanks

**Pull request merged**
