### PR TITLE
Public peer around SF, CA, USA ("salesforce-tower")

### PR DESCRIPTION
**Pull request by belovachap**
Hello!

I have a droplet in a SF data center that folks can connect to if they're looking for a connection :)

### CODE REVIEW

**Comment by ansuz** [comment]
Great, I'll merge this later tonight.

**Comment by ansuz** [comment]
Oops, I forgot to merge this. Thanks!

**Comment by ansuz** [comment]
Now listed on the API server at https://peers.fc00.io/1/location/san-francisco

**Comment by belovachap** [comment]
ty much! :)

**Pull request merged**
