### PR TITLE
Create irvineca.usa.k

### PR DESCRIPTION
**Pull request by kylerschin**
this is my peer....

### CODE REVIEW

**Comment by ansuz** [comment]
The check fails because it expects your credentials to be valid JSON.

You can compare against [this file](https://github.com/hyperboria/peers/blob/master/EU/fr/strasbourg/magik6k.net.k).

Once that passes we can merge.

**Comment by kylerschin** [comment]
i fixed the json. Will you accept it now?

**Comment by kylerschin** [comment]
its good now!

**Comment by kylerschin** [comment]
ok... to many build errors. i think i need help.

**Comment by thefinn93** [comment]
You know you can run the tests yourself... Try making sure that passes before committing. Also, not sure what's wrong, i'll take a look

**Comment by kylerschin** [comment]
thanks thefinn93!

**Comment by thefinn93** [comment]
And `./tests.py` has a `--clean` flag, which in this case does this:


```patch
diff --git a/NA/us/california/irvineca.usa.k b/NA/us/california/irvineca.usa.k
index e71341f..2885f67 100644
--- a/NA/us/california/irvineca.usa.k
+++ b/NA/us/california/irvineca.usa.k
@@ -1,9 +1,9 @@
 {
     "68.96.88.249:46242":{
-            "contact":"kylerschin@gmail.com",
-            "password":"1xbcjwq85z5qwmhjx1kclsx390yjl36",
-            "login": "default-login",
-            "peerName":"glitchedpixels-server",
-            "publicKey":"p0j807r0cqsmm690wrbvljtxgkunn369hw9wknly307z6lhsj2w0.k"
+        "contact":"kylerschin@gmail.com",
+        "login":"default-login",
+        "password":"1xbcjwq85z5qwmhjx1kclsx390yjl36",
+        "peerName":"glitchedpixels-server",
+        "publicKey":"p0j807r0cqsmm690wrbvljtxgkunn369hw9wknly307z6lhsj2w0.k"
     }
 }
```

looks like you just had the wrong indentation.

**Comment by kylerschin** [comment]
so. how can i fix it?

**Comment by thefinn93** [comment]
Fix your indentation, apply that patch or run `./tests.py --clean`

**Comment by kylerschin** [comment]
i'm still confused. I removed the tabs and it still didn't work. :-(

**Comment by thefinn93** [comment]
Try `./tests.py --clean`

**Comment by kylerschin** [comment]
IT WORKS! IT WORKS! IT WORKS! I am about to cry! It works!

**Comment by kylerschin** [comment]
*crowd chants*
merge merge merge
MERGE! MERGE! MERGE!
##MERGE! MERGE! MERGE!
#MERGE! MERGE! MERGE!

**Comment by thefinn93** [comment]
YAY!

**Comment by ansuz** [comment]
:+1:

**Pull request closed without merging**
