### PR TITLE
Additional cwningen.cymru node in Amsterdam (IPv6 only)

### PR DESCRIPTION
**Pull request by cwningen**

### CODE REVIEW

**Comment by thefinn93** [comment]
Could we get the full GPG key fingerprint?

**Comment by thefinn93** [comment]
[More information on why that might be a good idea](https://evil32.com/)

**Comment by cwningen** [comment]
I couldn't find any example formats so changed gpg field to fingerprint and added gpg-public-key with a link to HTTPS download of the public key.

**Comment by ansuz** [comment]
The format can be seen in several of the other credential files:

https://github.com/hyperboria/peers/blob/master/EU/de/hesse/h.ancha.lurk.space.k#L4

16 bytes, hexadecimal, all caps, no spaces.

**Comment by cwningen** [comment]
Okiedoke. Have updated the format and pushed new commit

**Comment by ansuz** [comment]
Thanks!

**Pull request merged**
