### PR TITLE
Pretty JSON

### PR DESCRIPTION
**Pull request by thefinn93**
Along the lines of #40, but with actual JSON that can be parsed without modification by any JSON parser, a `test.py` modification to check that future submissions comply with formatting guidelines, and a `test.py` flag (`--clean`) to auto-format your ugly submissions before you submit them

### CODE REVIEW

**Comment by Kubuxu** [comment]
LGTM, I would just like to hear @ansuz opinion about migrating to real JSON instead of object entry.

**Comment by ansuz** [comment]
As noted on irc, I'm happy with either format, but it should be well documented how things are supposed to be used.

Putting a **bold disclaimer** that the nested data structure is not copy-paste-able would help avoid newb errors (assuming they read the readme (probably a false assumption (but a fair one to make anyway))).

**Comment by Kubuxu** [comment]
_That are some Scheme level parenthesis._

and disclaimer would be nice.

**Comment by ansuz** [comment]
:+1:

**Comment by thefinn93** [comment]
sooo someone wanna add that however you want it phrased? This is a pull from another branch of this repo, y'all have access to it. Do that then merge this shit

**Comment by Kubuxu** [comment]
I am for merging it as it is, README requires total overhaul either way.

**Pull request merged**
