### PR TITLE
Some tags requiring location

### PR DESCRIPTION
**Pull request by kylerschin**

### CODE REVIEW

**Comment by kylerschin** [comment]
Hello?

**Comment by kpcyrd** [comment]
I think it's a good idea to have the data around, since traffic within providers is sometimes free. We should probably discuss how to have this data around in general.

@ansuz @dansup @thefinn93 @lgierth thoughts?

**Comment by kylerschin** [comment]
@kpcyrd @dansup @thefinn93 @lgierth @ansuz Any thoughts about formatting? Should there be spaces? hyphens?

**Comment by ansuz** [comment]
right now everything is sorted geographically, and https://peers.fc00.io leverages that to filter nodes.

If you modified the path of a node to use datacenter as an even more specific location than municipality, it would fit right in with that scheme.

> continent > region > municipality > datacenter > datacenter aisle > rack > etc.

**Comment by kylerschin** [comment]
Most Services only let you go down to the data center you are in. Anything else could be bad for the company.

**Comment by kylerschin** [comment]
@ansuz if everyone gave data, we could make a map of all peers and the links in between. To find out where a peer is, simply take the center of mass of all the peers. Then, just use fc00 data to draw the links.

**Comment by ansuz** [comment]
:ok:

**Comment by kylerschin** [comment]
@ansuz someone merge this.

**Pull request merged**
