### PR TITLE
quebec node

### PR DESCRIPTION
**Pull request by mixxit**
canada node

### CODE REVIEW

**Comment by Kubuxu** [comment]
Please upgrade your entry with new format. https://github.com/hyperboria/peers#json-formatting

**Comment by mixxit** [comment]
any ideas? sorry for all the attempts i need to setup python

**Comment by dansup** [comment]
looks good to me. @kubuxu maybe you could be a bit more descriptive next
time.

**Comment by Kubuxu** [comment]
Sorry, the format is: valid JSON, space after colon, indentation using 4 spaces.

**Pull request closed without merging**
