### PR TITLE
Create kaotisk.rethymno-meshnet

### PR DESCRIPTION
**Pull request by kaotisk-hund**
added my node

### CODE REVIEW

**Comment by Kubuxu** [comment]
The `login` field is indented with tab, could you fix it?

**Comment by kaotisk-hund** [comment]
removed tab and also put the file under a city folder

**Comment by Kubuxu** [comment]
Also your file should have `.k` extension.

**Comment by kaotisk-hund** [comment]
ok done.

**Comment by Kubuxu** [comment]
Thanks

**Pull request merged**
