### PR TITLE
remove nodes which rely on dns

### PR DESCRIPTION
**Pull request by ansuz**
I resolved the dns records for all credentials that didn't use raw IPs and replaced the domains with the results.

### CODE REVIEW

**Comment by thefinn93** [comment]
Have you checked with the owner of those nodes? Or is it you?

**Comment by ansuz** [comment]
I didn't check with anyone, but [this PR to cjdelisle/cjdns](https://github.com/cjdelisle/cjdns/pull/949) will break support for hostnames, and cjd has said he plans to merge it.

@kaotisk-hund has said that his nodes have dynamic IPs. I'm not sure about @mixxit's.

**Comment by mixxit** [comment]
You can remove mine they don't exist any more

**Comment by thefinn93** [comment]
I'm all in favor of removing DNS stuff, but if the IPs are dynamic then we should just remove the nodes from the list.

**Comment by ansuz** [comment]
that just leaves @kaotisk-hund's node: https://github.com/hyperboria/peers/blob/master/EU/gr/rethymno/kaotisk.rethymno-meshnet.k

**Pull request merged**
