### PR TITLE
Additional cwningen.cymru node

### PR DESCRIPTION
**Pull request by cwningen**

### CODE REVIEW

**Comment by thefinn93** [comment]
Wow, not sure why no one got to this until now. Could you pull from upstream so we can easily merge? Then I'll merge it

**Comment by cwningen** [comment]
Sure!

**Comment by thefinn93** [comment]
Oh you didn't need to close! Just pull from upstream master, merge it into the branch you PR'd from and push

**Comment by cwningen** [comment]
Apologies, not particularly familiar with github usage.. I believe I've now done that..

**Comment by ansuz** [comment]
looks good to me.

**Comment by thefinn93** [comment]
no worries, looks good, merging!

**Pull request merged**
