### PR TITLE
EU/sthlm: Drop leeloo

### PR DESCRIPTION
**Pull request by kyrias**
Due to a move I no longer control the network I'm using so can't open
ports anymore.  I do however still have the possibilyt of outgoing peering.

---

(Wonder if it would be worth it, making a list of outgoing-only peers...)

### CODE REVIEW

**Comment by ansuz** [comment]
that's an interesting idea, but I think a mailing list might be a more suitable medium.

**Comment by kyrias** [comment]
Probably, yeah.

**Comment by cschmittiey** [comment]
+1 on the mailing list idea

**Comment by ansuz** [comment]
I think there was such a mailing list at one point, but I don't know if it's still alive.

@thefinn93 ?

**Comment by thefinn93** [comment]
https://lists.projectmesh.net should still be up and functioning, although I'd like to rebuild it on a new server...

**Comment by kyrias** [comment]
@thefinn93 Poke me if you want any help with that.

**Comment by thefinn93** [comment]
Need to figure out how to move gnu mailman. It shouldn't be hard, just requires me to actually read some docs.

**Pull request merged**
