### PR TITLE
Create nat.usa.k

### PR DESCRIPTION
**Pull request by NateBrune**

### CODE REVIEW

**Comment by thefinn93** [comment]
You could try running the tests locally before pushing...

**Comment by NateBrune** [comment]
Nailed it first try.
Seriously though, this node will be well maintained. If it goes offline I will remove it from the list.

**Comment by thefinn93** [comment]
```
gpg: requesting key 6735BAD7 from hkp server pgp.mit.edu
gpgkeys: key C95CE6BC6735BAD7 not found on keyserver
```

```
gpg: requesting key 6735BAD7 from hkp server keys.gnupg.net
gpgkeys: key C95CE6BC6735BAD7 not found on keyserver
```

**Comment by NateBrune** [comment]
https://pgp.mit.edu/pks/lookup?op=get&search=0xC95CE6BC6735BAD7

pgp key is now submitted to keyserver.

**Pull request merged**
