### PR TITLE
Add leelo.kyriasis.com

### PR DESCRIPTION
**Pull request by kyrias**

### CODE REVIEW

**Comment by cschmittiey** [comment]
Looks good to me! @ansuz is it alright if I merge this?

**Comment by cschmittiey** [comment]
<derp> cSmith, you do not need permission
<@derp> if you have github org creds already, looks good to me

**Comment by ansuz** [comment]
It looks a little long, @kyrias, have you confirmed that it doesn't [overflow](https://github.com/hyperboria/docs/blob/master/bugs/connectTo-overflow.md)?

**Comment by kyrias** [comment]
Ah, damned, seems the version I tested wasn't the one I had added, sorry. Sec.

**Comment by kyrias** [comment]
Fixed in #17

**Pull request merged**
