### PR TITLE
Add Computer-Pig node

### PR DESCRIPTION
**Pull request by happysmash27**

### CODE REVIEW

**Comment by ansuz** [comment]
I you run the test script (`./tests.py --clean`) it will reformat your credentials such that they pass the test, then I'll merge.

**Comment by wfleurant** [comment]
@happysmash27 ping

**Comment by ansuz** [comment]
https://github.com/hyperboria/peers/blob/master/tests.py

You'll have to run that command in the peers repo directory root.

**Comment by ansuz** [comment]
thanks

**Comment by happysmash27** [comment]
Thanks! Finished.

**Pull request merged**
