### PR TITLE
don't try to validate files which don't end in .k

### PR DESCRIPTION
**Pull request by ansuz**

### CODE REVIEW

**Comment by thefinn93** [comment]
Why would we allow invalid files?

**Comment by thefinn93** [comment]
And if we were to implement this, we should put it in the for loop, not the `validate()` function

**Comment by wfleurant** [comment]
so when implementing a new required field or suggested field we should `pass` instead of the `sys.exit(1)`.. we do not validate a files ending in .foo, but we still return True

**Comment by thefinn93** [comment]
The validator should validate files with unexpected keys, as long as the required fields are there.

**Comment by ansuz** [comment]
It seems I had some junk files in the repo that were failing the tests (I thought they were a part of the repo). I was ignoring those.

I'll undo the test changes and just PR the readme.

**Comment by ansuz** [comment]
merged readme changes

**Pull request merged**
