### PR TITLE
add h.totem.tfnux.org.k

### PR DESCRIPTION
**Pull request by adraenwan**

### CODE REVIEW

**Comment by wfleurant** [comment]
i tested the IP6 entry alone. It caused cjdns to fail when starting

next, i removed GPG entry, restarted, and it worked.



```
1524070744 DEBUG AdminClient.c:333 Connecting to [127.0.0.1:11234]
1524070744 INFO Configurator.c:135 Checking authorized password 0.
1524070744 INFO Configurator.c:159 Adding authorized password #[0] for user [default-login].
1524070749 CRITICAL Configurator.c:97 Failed to make function call [Timed out waiting for a response], error: [UDPInterface_beginConnection]
1524070749 CRITICAL Configurator.c:57 enable Log_LEVEL=KEYS to see message content.
1524070749 CRITICAL Configurator.c:71 Aborting.

```

**Comment by wfleurant** [comment]
I tested with IP4, same issue. I removed extra 'ipv6' entry, and it worked.

**Comment by ansuz** [comment]
IIRC, there was supposed to be some change in the configurator which ignored extraneous fields. I could be misremembering this, though. I did debug a similar issue something like three years ago, and I found that the bencoded data was overflowing UDP's limits.

**Comment by ansuz** [comment]
see https://github.com/hyperboria/docs/blob/master/bugs/connectTo-overflow.md

**Comment by lzsaver** [comment]
I confirm that this config does not work - not short enough.
```
# cjdroute --version
Cjdns version: cjdns-20.2-5.el7
Cjdns protocol version: 20
```

**Pull request merged**
