### PR TITLE
Change IP address

### PR DESCRIPTION
**Pull request by kylerchin**

### CODE REVIEW

**Comment by wfleurant** [comment]
@kylerchin you've removed the hostname/ip?

**Comment by kylerchin** [comment]
@wfleurant Sorry this took a while, fixed it!

**Comment by kylerchin** [comment]
@wfleurant ping again?

**Comment by kylerchin** [comment]
Is anyone here? @kpcyrd @kyrias @lukevers @benhylau or is this repo dead?

**Pull request merged**
