### PR TITLE
fix issue #128

### PR DESCRIPTION
**Pull request by adraenwan**
see #126 and #128

### CODE REVIEW

**Comment by FinlayDaG33k** [comment]
You do know that JSON does not support commenting right?  
Also, as far as I know, having the contact field is required.

**Comment by cwchristerw** [comment]
Cjdns actually supports at least # comments

**Comment by adraenwan** [comment]
i don;t understand: my pull request is OK for travis, but does not appear un the repo....

**Comment by adraenwan** [comment]
> Cjdns actually supports at least # comments, i use them

Yes it also support // comments, like JS.
But the problem is the parser, more restrictive than the actual cjdns implementation.

**Comment by adraenwan** [comment]
Any reason why this PR is not merged ?

**Pull request merged**
